In [14]:
from sklearn.preprocessing import StandardScaler,robust_scale,minmax_scale
scalar=StandardScaler()
from sklearn.model_selection import train_test_split

In [15]:
import pandas as pd

In [16]:
df=pd.read_csv("standardscaler.csv")

In [17]:
df.head(2)

   Feature1  Feature2      Feature3         Target
0         7    506815  78179.054805  147107.322662
1         4    293822  70538.588873  127684.231772

In [18]:
x=df.drop(columns='Target')
y=df['Target']

In [19]:
xtrain,xtest,ytrain,ytest = train_test_split(x, y,random_state=42, train_size=0.8)

In [20]:
scalar=StandardScaler()

In [21]:
xtrain_scaled=scalar.fit_transform(xtrain)
xtest_scaled=scalar.transform(xtest)

In [26]:
xtrain_scaled

array([[ 0.04029928,  1.35016187, -1.2832588 ],
       [ 0.4287261 ,  1.27673624,  0.68899671],
       [ 1.20557975,  0.7159433 ,  1.38675154],
       ...,
       [-1.513408  ,  1.23046416, -0.17710939],
       [-1.12498118,  1.4513411 , -0.41686935],
       [-0.73655436, -0.71808777, -0.06822929]], shape=(800, 3))

In [29]:
xtrain_scaled.mean(axis=1)

array([ 3.57341190e-02,  7.98153019e-01,  1.10275819e+00,  5.38524260e-01,
        2.87805102e-02, -2.12099670e-01, -3.63057441e-01, -2.36394238e-01,
        3.09721143e-01,  3.82356184e-01,  3.18807441e-01, -2.19458181e-01,
        7.17763051e-01,  3.54474397e-01,  1.02410951e+00,  6.65945608e-01,
       -1.26987782e-01, -1.56691798e-01, -2.14313004e-01,  6.49824453e-01,
        3.45854476e-01,  2.72227829e-01, -3.87460374e-01, -2.02618507e-01,
       -5.39514811e-01, -1.68387388e-01, -3.53857723e-01, -3.61181503e-01,
        2.82433434e-01,  4.36540498e-01, -3.87077814e-01, -5.50197388e-01,
        1.65179926e-01,  2.85070091e-01,  2.80417375e-01, -3.23540614e-02,
        6.51463978e-01, -1.95634534e-01, -5.19013779e-01,  8.49822964e-01,
        5.13133248e-01,  2.51481319e-01, -1.55432095e+00, -7.84112018e-02,
        2.68130311e-01,  4.35811887e-02, -2.58936225e-01,  4.19679370e-01,
        3.71257333e-01,  5.22621549e-01, -1.16068154e+00,  1.76520395e-01,
        4.15636791e-01,  6.96872225e-01,  5.28238651e-01, -3.51209194e-02,
        3.20340277e-01, -3.10813311e-01,  1.40558972e+00, -4.08972250e-01,
        1.04842663e-01,  7.62322937e-01,  2.80229978e-01, -7.39155687e-01,
       -1.33812377e+00, -1.18064304e+00,  2.18199015e-01, -6.31044480e-02,
       -3.47221303e-01, -5.89243791e-01,  8.24689406e-01, -5.87492432e-01,
        6.06488438e-01,  3.29996742e-01, -1.71214508e-01, -4.91162432e-01,
        4.07445620e-01, -7.16261260e-01, -1.43692681e-01, -6.82128295e-01,
       -8.48688710e-01, -5.73263344e-01, -4.73962003e-01, -1.37115155e-02,
       -6.05655566e-01,  1.13449033e+00,  9.61221736e-01, -6.21325512e-01,
        5.34332214e-01, -3.51242649e-01,  4.75369830e-01, -7.83511224e-02,
        3.12572847e-02, -4.27137429e-01, -1.10546270e-01,  1.88454203e-01,
        5.58981825e-01, -3.86868019e-01,  1.15707234e+00, -8.62281326e-01,
       -2.94875614e-02, -7.91577133e-02,  7.35637261e-01,  2.88205851e-01,
       -1.20057012e-01,  5.40012705e-01,  4.48917854e-02, -2.24878148e-01,
       -2.56882039e-02,  1.36793583e-01, -4.30386762e-01, -1.71851106e-01,
        6.85157434e-01,  6.35429958e-01, -6.58168449e-01, -7.17965238e-01,
       -1.55436413e-02,  4.60271954e-01, -4.23972638e-01, -2.49591927e-01,
        2.51248276e-01, -4.05572746e-01, -8.79948951e-01,  4.78855191e-01,
       -9.96674634e-02,  7.81378389e-02,  1.22844666e-01, -8.60760549e-01,
        1.48757131e-01,  9.77311819e-01,  2.64094922e-01, -1.74058314e-02,
        2.82629847e-01, -2.65981018e-01,  5.83045109e-01,  4.24614285e-01,
        3.52451387e-01,  8.53905048e-02,  6.63270076e-01, -4.89971000e-01,
        6.11127817e-01,  1.00755655e-01,  1.79722235e-01,  3.47641461e-01,
       -7.19381112e-01,  5.40627646e-01, -3.79622865e-01,  4.11610048e-01,
       -9.03880626e-01, -2.14402295e-01, -1.38538780e-02,  1.65967044e-01,
       -6.32983938e-02, -1.58113452e-01,  2.57024682e-01, -4.40558881e-01,
       -5.40760193e-01, -1.80810625e-02,  6.64485225e-01, -2.99103907e-01,
       -6.08871516e-01, -4.02813063e-01, -5.26040245e-01,  1.88150086e-01,
       -1.81207106e-01, -2.29665913e-01,  8.30464479e-02, -3.39298783e-01,
       -8.67987673e-01, -5.02568991e-01, -1.50087063e-01,  3.32911981e-01,
       -1.19039742e+00, -5.45630601e-02, -3.44339284e-01,  1.00731420e-01,
        6.37315850e-01,  6.37229889e-01,  5.65805870e-01,  4.55084751e-01,
       -1.01855779e+00, -2.20846732e-01, -8.62767083e-01,  1.00021799e+00,
        2.43918669e-01, -8.70348899e-01, -5.40511577e-01,  2.76954740e-01,
        6.91847912e-03, -9.46130567e-01, -3.08798621e-01,  3.39784230e-01,
       -5.50952019e-01, -1.74463289e-01,  2.00855626e-01, -1.60652210e-01,
        4.29331039e-01,  3.36631072e-01,  2.60850777e-01,  1.18317845e+00,
       -4.92795349e-02, -6.51295570e-02,  8.04546519e-01,  3.45309629e-01,
       -1.10417464e-01, -2.12575137e-01, -2.95835532e-01, -2.57142780e-01,
        6.16167003e-01, -1.04597746e+00,  7.52598671e-02,  3.78399943e-01,
       -6.38359876e-01, -1.19669501e-01, -5.56883298e-01,  4.63136094e-01,
       -9.00461016e-02,  5.31109853e-01, -3.72643192e-02,  1.59234633e-01,
       -1.04925886e+00,  7.83908486e-02,  1.40203585e+00,  9.91991529e-01,
       -1.78773522e-01, -2.31437623e-01, -4.23002990e-01,  5.97332024e-01,
        1.26123207e-02, -1.32202643e+00, -4.62449373e-01, -3.63700510e-01,
       -1.26343491e-01, -1.30617870e+00,  1.54908967e-01, -3.78078063e-01,
       -8.85049895e-01, -8.01943207e-01, -2.03766774e-01,  8.75844251e-02,
       -9.05651112e-04, -7.35371935e-01,  7.25194744e-01,  3.29870260e-01,
       -3.52242640e-01,  4.42208920e-01, -1.01462349e-01,  6.99886362e-01,
       -3.24675033e-01,  7.84455895e-01, -4.59619286e-01, -4.26576632e-01,
       -2.04567994e-01, -8.98309598e-02, -7.78335223e-02,  5.23069594e-01,
        2.80657592e-01, -2.11162433e-01, -4.10343209e-01, -5.66776558e-01,
        2.23984019e-01,  1.91738630e-01,  2.90857031e-01,  5.40455695e-01,
        5.20038037e-01,  4.42823272e-01, -9.02179509e-02, -1.26248498e-01,
       -2.49620363e-01,  3.22100133e-01,  2.69365856e-01,  8.21660029e-01,
        2.33480208e-01, -1.31225630e+00,  1.67591149e-01, -9.40358060e-01,
       -2.27434649e-01, -3.81042253e-01, -5.84835415e-01, -7.33309496e-01,
       -1.52367522e-01,  5.08122250e-01,  1.34227816e-02,  3.68117647e-03,
       -2.85493301e-01,  6.09105614e-01,  6.55056710e-01,  7.47145416e-01,
       -6.43599952e-02,  7.56978623e-01, -6.09351657e-01, -4.77143399e-01,
        3.18417429e-01, -6.39765153e-01,  7.62336619e-03, -6.48359342e-01,
        8.43654822e-01, -3.38938475e-01,  7.24937576e-02, -1.48911818e-01,
        6.76075943e-01, -5.37322459e-01, -4.48052113e-01, -6.36574728e-01,
       -3.91535768e-01,  6.13531184e-01, -1.84862560e-01,  4.08158525e-01,
        8.95622937e-02, -4.86974676e-02,  6.00092552e-01, -1.17647742e-01,
        7.19421565e-02, -8.85812307e-01,  1.41129622e-01,  4.81247451e-01,
       -4.12692724e-01, -5.60508761e-01, -1.20719635e-01,  8.55514112e-01,
       -9.06021335e-01, -7.36917393e-01,  4.85606524e-01, -5.62938464e-01,
       -2.64069900e-01,  2.37753668e-02, -1.21597146e-01, -3.57132339e-01,
       -1.06924409e+00,  4.98105455e-01,  4.22265756e-01,  1.27357507e+00,
        2.92148117e-01,  6.31334062e-01, -4.04791943e-01, -2.81642330e-01,
        1.51377944e-02,  5.41504611e-01,  4.92982365e-02,  6.97646461e-01,
       -5.82371648e-01, -2.82816808e-01,  8.39851806e-01,  5.51296769e-01,
       -4.59440655e-01, -1.52022696e-01, -7.32633102e-01,  9.16259952e-01,
        3.00674912e-03,  7.91059598e-01, -2.40070458e-01, -7.48969724e-01,
        8.45483212e-01, -3.74719575e-01,  3.02151377e-02, -5.07858930e-01,
        4.20350348e-01, -4.49890924e-01, -5.51998176e-01,  3.50908020e-01,
       -6.40709822e-01, -3.34751743e-01,  1.80243975e-01, -3.11280124e-01,
        6.19085559e-01,  2.64588353e-02,  1.71139164e-02,  2.34128506e-01,
        6.99174812e-01, -9.00896569e-01,  4.22153788e-01,  1.31627179e-01,
        1.88569273e-01,  9.10251324e-02,  7.23769731e-01,  8.47871417e-01,
        1.79802000e-01,  7.52869405e-01,  6.98237169e-01, -5.48167393e-01,
       -7.08262389e-01,  3.98424099e-01, -1.56130358e-01, -1.05155375e+00,
        1.12930979e+00,  6.79634682e-02,  4.94368698e-01,  1.42627591e-01,
       -9.84476697e-01, -4.26707923e-01, -1.03206943e+00,  1.37230202e+00,
       -8.23883658e-01,  2.30024150e-01, -5.29172870e-01, -5.00867515e-02,
       -6.82311273e-01,  2.46014712e-03, -5.69042168e-01,  7.40029237e-01,
        4.51303058e-01,  2.19619841e-01, -6.23822773e-01, -5.16604276e-03,
       -5.58038143e-01, -5.59058053e-01,  4.32048206e-01, -1.15087558e-01,
        6.03422022e-01, -2.01578552e-01,  5.34142395e-01, -2.06955635e-01,
        1.86571462e-01,  5.96593433e-01,  1.07986818e+00, -8.45680899e-01,
       -8.13454560e-02, -4.68635801e-01,  8.97567775e-01, -3.39392230e-02,
       -1.36451633e-02, -7.12911741e-01,  1.72910259e-01,  1.59089559e-01,
        2.79575216e-01, -8.63480802e-01, -4.74299827e-01, -1.52966555e-01,
        9.09436212e-01,  5.42870021e-02, -6.04115221e-01,  5.99349017e-01,
        4.76185517e-01, -6.38000647e-01,  2.81597819e-01,  1.42312407e-01,
        3.54133035e-01, -5.00749104e-01, -2.10189893e-02, -4.18210195e-02,
        2.30838691e-02, -2.03056765e-01,  4.47663931e-01, -4.22094630e-01,
       -2.40516629e-02, -4.77126426e-02,  1.07786317e+00,  2.13834632e-01,
       -5.59468600e-01,  2.03896851e-01,  8.37047032e-01, -2.63694028e-02,
       -5.98006088e-01, -2.58730977e-01, -5.43923304e-01,  4.07195373e-01,
       -1.11902006e-01, -4.85917792e-01,  5.74205730e-01, -3.71525290e-01,
       -8.85632099e-01,  2.16774552e-01, -8.62198415e-01, -7.99572187e-02,
       -8.11176618e-01, -4.48708394e-01, -3.36478973e-01, -1.08815080e+00,
        5.99056475e-01, -4.51051107e-02, -8.74822506e-01, -3.80242349e-01,
        2.15114152e-01, -1.00033313e-01, -1.36322610e-01,  8.24318194e-02,
       -7.95254863e-01, -1.66437834e-01, -2.05563195e-01,  6.55896487e-01,
        8.54666771e-01, -1.23938119e-01, -3.12199033e-01, -4.67661400e-01,
        1.10001844e+00, -1.37222873e-01,  4.84250815e-01,  7.23708304e-01,
       -1.05856023e+00,  9.84746866e-01, -4.82072432e-01, -6.59749338e-01,
       -9.18739574e-01,  1.26742675e-01,  4.02914036e-01, -1.47505286e-01,
        8.64989528e-01,  1.19495686e+00,  1.33456191e-01,  2.94735676e-01,
       -1.84189794e-01, -8.80575314e-01,  2.36864690e-01, -8.56425675e-01,
       -5.22608955e-02,  3.31560076e-01, -2.95822512e-01, -1.48484061e-01,
        8.37601201e-01,  1.46047693e-01,  6.68411209e-01, -1.27960465e-01,
       -2.28066167e-01, -2.96504633e-01, -6.85477466e-01, -1.23839121e-01,
        3.26882903e-01,  8.08038183e-01,  1.90332618e-01,  6.45602430e-01,
       -5.18529665e-01,  2.13989087e-01, -6.27775124e-01,  6.44531247e-01,
       -2.91394411e-01, -3.67814894e-01,  1.75907067e-01,  6.06671924e-01,
        8.08202252e-02,  5.00700092e-01, -1.04700680e+00, -9.88694763e-01,
       -7.42187432e-01, -8.76661222e-01,  1.82553740e-01, -2.28659756e-01,
        2.35822545e-01, -1.05590507e-01,  1.19293399e+00,  4.28091724e-02,
        3.21402754e-01, -6.88778415e-01,  8.52000266e-01,  9.55053455e-01,
       -3.57906505e-01,  8.23404280e-02,  1.23944325e+00,  5.95000444e-01,
        6.83501424e-01,  2.15929387e-01,  8.73869941e-01,  1.17195887e+00,
       -6.91574519e-01,  7.17068851e-01,  1.73054002e-01,  1.23371145e-01,
        1.67673528e-01,  5.79177750e-01, -5.25419795e-01,  4.33675901e-01,
        1.78538899e-01,  9.13101981e-02, -8.98901581e-01,  1.90687333e-01,
        6.55134900e-01, -1.77889731e-01, -4.72292173e-01, -8.63333669e-01,
       -2.73330236e-01, -3.93552152e-01,  8.24154234e-02, -2.42046537e-01,
       -4.18440188e-01,  7.50423604e-01,  4.82045570e-01, -3.73658120e-01,
        8.17009146e-01, -3.14529577e-02,  7.19800986e-01,  1.14135317e+00,
       -6.60325075e-01,  5.26952097e-02, -3.12401885e-01, -1.46385108e-02,
        6.85122822e-01, -3.47694114e-01,  1.11925029e+00, -1.87958410e-01,
        2.42566432e-01,  1.16305986e+00, -7.61229977e-01, -5.63678975e-01,
       -1.94282977e-01,  6.24178038e-01,  3.73905634e-01,  4.47663148e-02,
       -4.46818577e-01,  5.57060942e-01, -3.08171808e-01, -7.84173415e-01,
        2.16481594e-03, -1.10828501e-01, -3.31395912e-01,  5.95182165e-01,
        2.37780440e-01,  3.97273585e-01, -3.75081648e-01,  9.82135720e-02,
       -9.77358432e-01, -1.27652284e+00, -1.21792517e-01, -2.59963719e-01,
       -4.80124203e-02, -4.47951418e-01, -3.69468173e-01,  1.24719247e-01,
        3.08106856e-01, -7.03707218e-02,  4.35180550e-01, -4.16919760e-01,
        7.80749037e-01, -2.89892900e-01, -4.60762201e-01, -1.10045083e-01,
        1.28401879e-01,  1.05511670e+00,  5.19459479e-01, -5.20969597e-02,
        1.20374030e+00, -2.18278208e-01, -3.18568309e-02,  1.02701478e+00,
        3.95646617e-02, -6.89730809e-01,  6.28679155e-01,  3.42507660e-01,
       -1.45050848e-01,  4.35538199e-01, -1.25446480e-01, -3.55965607e-01,
       -4.81685067e-01,  2.72034614e-01, -7.56183634e-02, -1.26550150e+00,
        2.47937988e-01, -6.60212175e-01, -7.41961764e-01, -1.10224348e+00,
        2.66046299e-01,  2.18764011e-01,  8.08690033e-01,  2.31906013e-01,
        4.06123864e-01,  7.94498704e-02, -6.58571538e-01,  1.18080130e-01,
        1.56024968e-01,  1.20279375e-01, -4.61817487e-01, -6.11480402e-01,
        2.89547839e-01,  4.25628080e-01, -6.53685965e-01,  7.56992015e-01,
        2.21673229e-01,  4.72009835e-01, -1.80582417e-01,  6.21960948e-01,
        8.10172074e-01,  3.16265646e-01,  4.49778750e-01, -5.03374325e-01,
       -4.83674764e-01,  3.25937451e-02, -5.47721385e-02, -1.05244328e+00,
       -3.50292023e-01, -5.68625082e-01, -3.38170649e-01, -4.51762876e-01,
       -2.59720493e-01,  2.26705138e-01, -3.92398144e-01,  7.24381531e-01,
        1.49264141e-01,  8.79822528e-01, -1.20889307e-01, -3.70367145e-02,
        4.21918192e-01,  7.79081984e-01,  5.61555736e-01, -1.63878188e-01,
       -1.02190326e-01, -1.26710376e+00,  3.42794480e-01,  5.79002820e-01,
        7.73351433e-01,  1.00623667e-01,  6.48881941e-01, -5.53474137e-01,
       -2.13520977e-01,  9.15313056e-02, -1.12235317e+00,  1.09822033e+00,
        7.18410087e-01,  7.63324277e-01,  1.17720522e+00,  3.44838575e-01,
        1.85341416e-01,  7.49565939e-01,  7.66744007e-01, -1.01958810e-01,
        2.34909031e-01, -5.74533137e-01,  3.19695507e-01, -1.38390759e-01,
       -3.01296164e-01, -1.23460115e+00,  5.62713202e-01, -2.07230966e-01,
       -3.56570882e-02, -2.41283468e-01, -1.29400777e-01, -1.66446917e-02,
        2.96850254e-01, -3.66406124e-01,  1.29541513e+00,  5.81334284e-01,
       -3.22436263e-01,  3.16470073e-01,  4.11720927e-01, -3.34337518e-03,
       -9.39221283e-01, -7.03250219e-01, -4.22608654e-01, -8.57814071e-01,
       -7.49341334e-01, -4.11757453e-01, -3.65099503e-01, -8.91473725e-01,
       -3.58097630e-01,  7.24236399e-01, -4.32910558e-01, -3.06702272e-01,
       -1.78118558e-01, -2.37870463e-02,  9.72392971e-01,  4.19726824e-01,
        1.24329776e-02, -3.30910805e-01, -5.08751005e-01,  6.82448648e-01,
       -9.64968369e-01, -2.48337485e-01,  6.76350099e-01, -5.23023374e-01,
       -6.68844163e-01,  3.70835523e-01,  8.31135353e-01, -8.39913670e-01,
        4.07545515e-02, -4.62412830e-02, -4.74663702e-01,  8.14458678e-03,
       -3.77064209e-01, -1.70419869e-01, -4.82373262e-01, -6.01971401e-01,
       -1.04375744e-01, -5.21989098e-01,  4.69648415e-01,  2.49977564e-01,
       -1.15183838e+00, -4.93748584e-01, -2.67682910e-01, -8.22922661e-01,
       -1.86900708e-01,  6.81260610e-02, -3.91965153e-01, -4.12030619e-01,
        7.85224031e-01,  6.46005140e-01,  7.31086568e-01, -5.38248150e-01,
       -2.14460577e-01,  1.88301036e-01,  5.33048023e-01, -5.51213258e-02,
        1.89122264e-01,  3.61577343e-01,  1.21183184e+00, -1.91276589e-01,
       -3.97244784e-01, -5.14910699e-01,  2.98423458e-01,  8.22073524e-01,
        4.51914970e-01, -1.53351079e-01, -3.01698107e-02, -5.07623805e-01])

In [30]:
xtrain_scaled.std(axis=1)

array([1.07509433, 0.35469858, 0.28334329, 0.93596982, 1.18575014,
       0.76146172, 1.40367466, 0.74727835, 0.36029834, 1.20229449,
       0.9811436 , 0.94445133, 0.75786523, 1.28430797, 0.17685265,
       0.56625791, 0.73512898, 0.99770104, 1.04739167, 0.44522405,
       0.52122257, 0.77504059, 0.53415463, 1.05321608, 0.29924561,
       1.11987052, 1.11877862, 0.81293565, 0.84287657, 0.34576268,
       0.99924312, 1.03768974, 1.12182343, 0.96079189, 1.34722093,
       0.86631115, 1.1158746 , 0.8671619 , 0.99588935, 0.52989524,
       0.5428901 , 0.73040506, 0.1157775 , 1.17014693, 0.43558491,
       0.55517856, 1.04653912, 0.9028988 , 0.35439507, 1.00545304,
       0.53723898, 0.55773171, 0.55501922, 0.58092188, 1.20529586,
       1.11917235, 0.71135354, 1.24591786, 0.13769812, 0.39760372,
       0.36575199, 0.82380583, 0.73645441, 0.67184654, 0.24901872,
       0.28879804, 0.98786469, 0.08198242, 1.2471355 , 1.03691674,
       0.46828122, 0.52489776, 0.77983206, 0.89006679, 0.8806222 ,
       0.30754489, 0.67635636, 0.90011424, 0.42419285, 0.70249306,
       0.62906571, 1.43177086, 1.05135117, 1.29308201, 0.67517846,
       0.72856699, 0.68183362, 0.77780675, 1.45130028, 0.85903896,
       1.27528821, 1.37302403, 0.922012  , 1.42948714, 1.0718241 ,
       0.65812589, 1.19074351, 0.63551148, 0.46227029, 0.76305346,
       0.35153997, 1.33699546, 0.43754244, 0.73860124, 1.22019598,
       0.11689121, 0.08034102, 0.53901784, 0.78792113, 0.87844869,
       0.8270049 , 0.67582521, 1.00537486, 0.82978901, 0.7748603 ,
       1.12407178, 0.97386997, 0.63568142, 1.12360629, 0.2122654 ,
       0.87863792, 0.79824715, 0.99935722, 1.15679327, 0.75472624,
       1.00711305, 0.96298276, 0.32017827, 1.17657671, 0.53582631,
       1.08061745, 0.91776036, 1.02873681, 1.34297496, 0.45726138,
       0.95685223, 1.39939809, 0.90632737, 1.03662903, 0.88559041,
       1.23463681, 0.65225962, 0.78187214, 1.28564208, 0.92639536,
       0.78162864, 0.83862798, 0.22991719, 1.00002084, 0.4971741 ,
       0.76606424, 0.96203966, 0.30434284, 1.24150612, 0.16540515,
       1.44501505, 1.25359265, 1.29311407, 0.25159275, 1.08797189,
       0.48225832, 1.4169063 , 1.03423241, 1.28555146, 1.11725756,
       0.36766274, 0.8580219 , 0.69432917, 0.94089079, 1.20949295,
       0.62244498, 0.86547808, 0.39078869, 0.92859965, 0.9891449 ,
       0.36658208, 0.74278638, 0.8906696 , 0.66172731, 0.56599749,
       0.1345989 , 1.36827286, 0.32993575, 0.46301895, 0.50908887,
       0.71678436, 1.08575367, 0.70157491, 1.25440951, 0.16146433,
       1.31621936, 1.11333849, 0.49467148, 0.92429692, 0.51794067,
       0.68273871, 1.38808487, 0.3490002 , 0.98458457, 0.59288126,
       0.48599089, 1.05873062, 0.81559924, 1.41878946, 1.09116368,
       0.77171049, 1.36442269, 0.52872601, 1.23134411, 0.50128407,
       1.21947729, 1.44593229, 0.48280562, 0.71331907, 0.42412525,
       0.91004642, 1.34937367, 0.13052573, 0.74664569, 1.21303192,
       0.54850369, 1.12587257, 0.13752413, 0.52407074, 0.44540725,
       1.10349561, 0.75641238, 1.19509354, 0.72056217, 0.36334621,
       0.36378388, 1.13176637, 0.60589072, 0.40564285, 0.09489283,
       0.65658987, 0.54427601, 0.43544857, 0.10451071, 1.00310369,
       0.89943234, 0.42551615, 0.43119396, 0.75414415, 0.06407448,
       1.38285302, 0.29629116, 0.35804919, 0.8752941 , 0.57243517,
       0.80495211, 0.13906594, 0.89085995, 0.85851327, 0.41935696,
       1.3702319 , 0.65409692, 0.69443445, 0.3606298 , 1.01477837,
       1.23900004, 0.25286468, 1.02802622, 0.8525877 , 0.34987907,
       0.47161536, 0.6518788 , 1.22433499, 0.60637009, 0.93142082,
       0.91715809, 0.66130387, 0.59582218, 0.2575022 , 0.49357292,
       0.44937351, 0.95005194, 0.60061493, 1.26759732, 0.65628274,
       0.89693238, 0.75666813, 1.21981342, 0.51786865, 0.87762272,
       0.77171629, 0.82373602, 0.24469539, 1.00802116, 0.78755662,
       0.69990556, 1.07629258, 0.07917364, 0.57238557, 1.27785427,
       0.40978259, 1.14939303, 0.63270796, 0.25267085, 0.14324245,
       0.93734258, 0.69591313, 0.7541181 , 0.49871435, 0.70225523,
       0.60735755, 1.06937431, 0.6657735 , 1.24307034, 1.03621885,
       0.44533141, 0.73985477, 0.9751147 , 0.51417406, 1.07057066,
       0.60392145, 0.73688678, 0.56504206, 1.24538812, 1.02915852,
       0.4581285 , 0.94973151, 0.40097315, 0.20869923, 1.30051383,
       0.81863451, 1.05149313, 0.66531824, 0.05310759, 0.50040483,
       0.34644385, 0.27131954, 1.14243922, 0.69306321, 0.90762323,
       0.93301029, 1.19992374, 0.69495127, 0.85424445, 0.95252715,
       0.72277508, 0.54927054, 0.54601021, 0.41454277, 0.90371404,
       0.36091685, 0.41704271, 0.51261965, 1.35282045, 0.6455868 ,
       0.12842803, 1.11714577, 0.5353974 , 0.67553753, 1.10122322,
       0.21143301, 0.27164091, 0.55730786, 1.2122519 , 0.99356198,
       0.62551155, 1.13681709, 1.16912041, 0.73574139, 0.43886002,
       1.20379715, 1.18399138, 0.50292817, 0.3192689 , 0.50799363,
       0.57407211, 0.34529422, 1.00271681, 0.66841406, 1.07987807,
       0.57234395, 0.72924571, 0.75724027, 1.03128208, 0.69096207,
       0.80770947, 0.57674217, 0.69104347, 0.50086145, 0.50174963,
       0.83015391, 0.98748508, 0.21613169, 0.09955081, 0.6052328 ,
       0.4863276 , 0.162571  , 0.34357301, 0.41905058, 0.68437454,
       0.85343237, 1.2890066 , 0.8283517 , 1.11109983, 0.28518042,
       0.16525719, 0.4710109 , 0.76640002, 0.92850151, 0.83657081,
       1.18356115, 0.88854672, 0.75659808, 0.5420563 , 0.6669863 ,
       0.20844766, 1.19532355, 0.71869996, 0.9482475 , 0.50980006,
       0.53972797, 1.05359576, 1.22356079, 0.56744379, 1.09179088,
       1.28780691, 0.63786873, 0.64483066, 0.9294511 , 0.76692034,
       0.57737983, 1.00263726, 1.00774328, 0.28853758, 1.13332604,
       1.24169968, 0.40325411, 1.40835995, 0.64166468, 0.48128912,
       1.3174426 , 0.70771079, 1.15811469, 0.59520129, 0.17267553,
       1.01483047, 0.23851914, 1.18129268, 0.94817759, 1.13724334,
       0.63149628, 0.19854   , 1.33067875, 0.43310519, 0.93049209,
       0.54337104, 1.25000498, 0.47477262, 0.82327789, 1.3263893 ,
       0.72039447, 0.71875918, 0.18026143, 0.43008864, 0.97181792,
       0.41421723, 1.06325756, 0.32330754, 1.00049615, 0.47954377,
       0.16181268, 1.11504224, 0.52178404, 1.22075317, 1.24173933,
       0.56364313, 1.21904007, 1.0733238 , 0.60672561, 0.79204425,
       1.3528366 , 0.45821355, 0.14727976, 0.76252965, 1.12068145,
       0.84425486, 1.12684959, 0.96174769, 0.58866984, 0.52239767,
       0.70457457, 0.98227775, 0.51015849, 0.3283399 , 0.5007512 ,
       1.24941341, 1.34097023, 0.21243054, 1.10350305, 1.08038513,
       0.41433815, 0.32609653, 0.29045257, 1.11085376, 0.54243836,
       0.7014255 , 0.7413508 , 1.13173661, 0.50169484, 0.38318857,
       0.75846168, 0.8844508 , 0.46204717, 0.59987613, 1.39118576,
       0.56077836, 0.86985144, 0.50478004, 0.67269992, 0.79450073,
       0.45783284, 0.14336133, 0.81847641, 0.54954896, 0.5523138 ,
       0.68243839, 0.55846827, 0.40580391, 0.5260143 , 1.10820827,
       1.3605576 , 1.03005004, 0.73674852, 1.25390766, 1.17276238,
       0.3435009 , 0.62953508, 0.83001332, 0.6273122 , 1.33869112,
       1.30334169, 0.20514976, 1.08644328, 0.39971608, 0.93335423,
       1.30352431, 0.61632983, 0.44100537, 0.50056039, 0.59318023,
       0.75093225, 0.45014854, 0.62442731, 0.47862361, 0.67639794,
       0.09856279, 0.17523842, 0.86077298, 0.83920672, 1.00356817,
       1.38519213, 1.20334269, 0.62297253, 0.87889542, 1.38323939,
       1.00606606, 0.9292282 , 0.54960895, 0.71419027, 0.40873863,
       1.22967124, 0.98400404, 0.40943605, 1.04676924, 0.89540067,
       0.56614458, 0.84801249, 0.49527192, 0.66000734, 1.13975078,
       1.16384551, 0.24877591, 0.89160412, 0.52735952, 0.23007826,
       0.893515  , 0.83975199, 0.97509332, 0.84025183, 0.73886314,
       1.09962896, 0.42003741, 0.5787328 , 0.15023009, 0.03778901,
       0.55815456, 0.1772842 , 0.52554023, 1.04711841, 0.64130268,
       1.2301326 , 0.61333733, 1.46478076, 1.13552557, 0.6520919 ,
       1.27793146, 1.16778205, 1.32994645, 0.42090533, 1.08098113,
       0.8681018 , 0.41922655, 0.96295652, 0.72715819, 0.25677216,
       1.17621103, 0.80062571, 1.16809061, 1.19020554, 0.62709697,
       1.09555363, 0.20468663, 1.11143893, 0.84344393, 1.01647954,
       0.35984437, 0.53103266, 0.59882521, 0.72356394, 0.69781957,
       0.7467129 , 0.48604123, 1.10374758, 0.11788371, 1.08774472,
       0.97662719, 0.40950109, 1.12787786, 0.60914714, 0.29381685,
       0.80295051, 0.23320507, 0.90229815, 0.98121502, 1.45909355,
       1.20177221, 1.09785215, 0.35683648, 0.40444278, 0.66110739,
       1.12495232, 0.54750736, 0.55850357, 0.6515499 , 0.74737449,
       0.61098731, 1.2443067 , 0.29556304, 1.15019211, 0.37958042,
       1.04608514, 0.84872409, 1.05946744, 0.97959858, 0.87988631,
       0.67286566, 0.88999728, 1.04261668, 0.62289417, 0.40553982,
       0.88285434, 1.03641848, 1.28022643, 0.94686299, 0.73543224,
       1.19018328, 1.53295848, 0.58358999, 0.30915253, 1.06790687,
       0.3478119 , 1.29886559, 0.81717786, 0.77025349, 1.2274141 ,
       0.40669698, 0.46131878, 0.91068955, 0.76753822, 1.08955848,
       0.53926727, 0.94586521, 0.61126626, 1.1094786 , 0.82820333,
       1.39932949, 1.22592524, 0.73269049, 0.10620534, 0.57177212,
       0.37751329, 0.31680603, 0.54939495, 1.23342735, 1.12313274,
       1.05013799, 0.80963866, 0.3837576 , 0.40595737, 0.27288317,
       0.63864214, 0.32296258, 1.33355492, 1.02857873, 0.3593007 ,
       0.51369775, 0.96167132, 0.85901689, 0.63136614, 1.34932667,
       0.63565994, 1.13524664, 0.62839078, 0.60352336, 0.46371125,
       0.49585153, 0.81205033, 0.39932035, 0.88679365, 0.82924278,
       0.480398  , 0.34141259, 0.40118608, 0.77242031, 0.68129434,
       0.79585142, 0.52084519, 0.78950793, 0.87775519, 0.63489441,
       0.88979923, 0.55117277, 0.23579567, 1.39894061, 0.12163541,
       0.69733922, 0.49884968, 0.20544644, 1.23586362, 1.08892996,
       1.20743188, 0.16227142, 1.00116352, 1.13914993, 0.72550566,
       1.24406385, 1.34539988, 0.4755359 , 0.5643947 , 0.73015483,
       0.948504  , 0.62156996, 0.87874058, 0.11887875, 0.35402644,
       1.00822877, 1.17938191, 1.02963408, 0.95149674, 1.1200159 ,
       1.05879807, 0.27858019, 0.18548083, 0.73992389, 0.5756013 ,
       0.59899733, 0.53799677, 0.15418519, 0.84630586, 1.38260479,
       0.87425018, 0.61911277, 1.1645476 , 0.93972105, 0.09208421,
       0.61914757, 0.67034737, 0.83558059, 1.16634128, 0.92578984,
       1.36918563, 0.45354294, 0.34252509, 0.44583863, 0.50322501,
       0.43622984, 0.96441718, 0.88688084, 0.67919738, 1.1717635 ,
       0.05402952, 0.60539124, 1.12030709, 1.08674177, 0.31079029])

In [23]:
xtest

     Feature1  Feature2      Feature3
521         5    873638  87426.259635
737         9    779513  75958.265053
740         6    161081  65166.826704
660         8    784204  49725.643306
411         3    303186  78248.514208
..        ...       ...           ...
408         2    327898   8261.858084
332         1    856778  35423.688621
208         4    276494  45685.918802
613         2    290227  73244.899939
78          1    964152  32838.189950

[200 rows x 3 columns]